# Generated by Django 5.0.7 on 2024-08-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_employee_start_date_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.PositiveIntegerField(auto_created=True, unique=True),
        ),
    ]
