# Generated by Django 5.0.7 on 2024-08-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_employee_address_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newhiretask',
            name='file_upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
