# Generated by Django 5.0.7 on 2024-08-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_newhiretask_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newhiretask',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
