# Generated by Django 5.0.7 on 2024-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_newhiretask_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newhiretask',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
