# Generated by Django 5.0.7 on 2024-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_newhiretask_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newhiretask',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('file_upload', 'File Upload'), ('text_input', 'Text Input')], max_length=50),
        ),
    ]
