# Generated by Django 5.0.7 on 2024-08-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_newhiretask_response_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='Searcee', max_length=50),
        ),
    ]
